daducci/COMMIT

commit/core.py, commit/trk2dictionary/trk2dictionary.cpp, commit/trk2dictionary/trk2dictionary.pyx, commit/trk2dictionary/trk2dictionary_c.cpp
*Conflict of barakovic:master and daducci:master solved
Generate a `dictionary_TRK_fibers.trk` file in the directory of COMMIT outputs. This file contains the fibers used in the dictionary.
Possibility to set `gen_trk = False` in `trk2dictionary.run()`.
Added documentation for `gen_trk` parameter.
The structure of the `DICTIONARY` change in three parts:
1- Rename of the variable:
`DICTIONARY['IC']['trkNorm']` ==> `DICTIONARY['TRK']['norm']`
2- Reintroduction of the length of each streamline
`DICTIONARY['TRK']['len']`
3- Boolean array that takes into account if the streamline is used in the dictionary:
`DICTIONARY['TRK']['kept']`
=> Generate .trk file of fibers used in the dictionary

commit/trk2dictionary/trk2dictionary.cpp, commit/trk2dictionary/trk2dictionary.pyx, commit/trk2dictionary/trk2dictionary_c.cpp
Added the possibility to shift the tractogram in x,y,z directions independently.
The previous variable `fiber_shift` is removed. Three new variables are added:`fiber_shiftX`, `fiber_shiftY` and `fiber_shiftZ`.
=> add fiber shift in x,y,z directions

commit/core.py
Fixed order of repetitions for each kernels. 
Checked that the norm of the matrix A generated with '`doNormalizeKernels' = False`
```
norm_A1 = np.linalg.norm(A,axis=0)`
```
is approximately equal to the norm calculate by COMMIT generate with '`doNormalizeKernels' = True`
```
norm1 = np.repeat(mit.KERNELS['wmr_norm'],nF)
norm2 = np.repeat(mit.KERNELS['wmh_norm'],nE)
norm3 = np.repeat(mit.KERNELS['iso_norm'],nV)
norm_fib = np.kron(np.ones(mit.KERNELS['wmr'].shape[0]), mit.DICTIONARY['TRK']['norm'])
norm_A2 =  np.hstack( (norm1*norm_fib,norm2,norm3) )
```
**norm_A1 ≈  norm_A2**
=> fixed preconditioning

commit/core.py
- Place mean b0 as the first volume of `self.niiDWI_img` when `doMergeB0 = True`
- Generate kernels using the new [`model.resample()`](https://github.com/daducci/AMICO/blob/16fd07d27edc7c0a5346855c82409df60e94ec00/amico/models.py#L103-L133) method in AMICO
- Close #17
=> BUG: Load_kernels is broken after mods in AMICO

commit/core.py, commit/trk2dictionary/trk2dictionary.pyx, commit/trk2dictionary/trk2dictionary_c.cpp
Currently, the maximum allowed dataset size is 256 voxels in any direction; this modifications allows for bigger datasets, for example when working on ex-vivo data or resampled datasets.
=> Allow using datasets bigger than 256x256x256

commit/trk2dictionary/trk2dictionary.pyx, commit/trk2dictionary/trk2dictionary_c.cpp
Introduces the possibility to blur the contributions of the streamlines to the voxels when these are determined with `trk2dictionary`.
Three parameters are added:
- `blur_radii`: determines the distance from the main streamline of the blurring in mm (default : [])
- `blur_samples`: how many sectors to sample perpendicularly to the main streamlines (default : [])
- `blur_sigma`: each contribution is damped as a Gaussian (default : 1.0)
NB: of course this procedures introduces many more segments to be evaluated during the optimization (the number of unknown, i.e. x, is unaltered), so the fit will take more time.
=> Add fiber blurring

commit/trk2dictionary/trk2dictionary_c.cpp
This lets you run trk2dictionary also on .trk files for which you have only reading privileges.
=> changed required privileges on the input tractogram in trk2dictionary

commit/proximals.pyx, commit/solvers.py
When using the new code (@matteofrigo ), sometimes (randomly) there is the following error:
> Python(80308,0x7fff8f699380) malloc: *** error for object 0x7ff19f64c400: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
The main issue is that when there aren't EC or ISO compartments and the `lambda` for a given regularization is set to zero, the `non_negativity` prox was calculated in any case for these compartments even though there weren't such coefficients. This could lead to accessing bad memory locations and generate _segfaults_.
=> Fix segfault when using new regularization scheme

commit/proximals.pyx, commit/solvers.py
This PR is a workaround for the issue #54. The idea is to prevent the user to specify the Linf-norm in the regularizer of gNNLS.
=> Temporary workaround for issue #54

commit/proximals.pyx, commit/solvers.py
This PR should be able to enable the following speed-up on the computation of omega and prox functions:
- about **450x** for `prox_group_sparsity` (from about 20.5 s to 48.2 ms)
- about **1400x** for `omega_group_sparsity` (from about 15.6 s to 11.2 ms)
The acceleration is achieved through a redesign of the data structure about the groups which allows a faster direct access to memory via `cython`.
=> Faster proxs and omegas

CHANGELOG.md, commit/trk2dictionary/trk2dictionary.pyx, commit/trk2dictionary/trk2dictionary_c.cpp, setup.py
Add parameter 'min_fiber_len' in trk2dictionary to discard streamlines shorter than this value (in mm)
=> Add parameter 'min_fiber_len' in trk2dictionary

commit/core.pyx, commit/operator/config.py, commit/operator/operator.pyxbld, setup.py
No change in behavior, simply allows build_operator() to choose where to build the extension.
This makes the usage of singularity compatible with commit.
=> Build operator in any folder

CHANGELOG.md, commit/core.pyx, setup.py
Adds the model-specific details of the adopted model, e.g. name, d_par, etc, inside the output results.pickle file. This additional feature requires the modifications made to AMICO in version 1.2.6.
=> Store model parameters to results.pickle

CHANGELOG.md, commit/core.pyx, commit/trk2dictionary/trk2dictionary_c.cpp, setup.py
In case of blur, i.e., when using the parameter `blur_sigma` in `trk2dictionary.run()`, the streamline weights returned in `streamline_weightx.txt` do not take into account the blur. This PR scales these values accordingly.
=> Streamline weights in case of blur

CHANGELOG.md, commit/__init__.py, commit/core.pyx, commit/info.py, setup.py
Allows the user to specify the string format when saving to `streamline_weights.txt` the estimated coefficients of the streamlines. this is done via the new parameter `coeffs_format` pf the `save_results()` function, and its default value is `%.5e` as it was before.
=> Save results format

CHANGELOG.md, commit/info.py, commit/trk2dictionary/trk2dictionary.pyx, commit/trk2dictionary/trk2dictionary_c.cpp
This patch should fix the occasional problem when loading a TCK tractogram constructed from very anisotropic data.
=> Fix affine when loading TCK tractograms

CHANGELOG.md, commit/core.pyx, commit/info.py
Added:
- 'replace_bad_voxels' parameter in 'load_data()' to replace NaN and Inf values in the signal
=> Data loading: check for "bad voxels" (NaN or Inf values) when load and pre-process data

CHANGELOG.md, LICENSE, commit/core.pyx, commit/models.py, commit/trk2dictionary/ProgressBar.h, commit/trk2dictionary/trk2dictionary.pyx, commit/trk2dictionary/trk2dictionary_c.cpp, requirements.txt, setup.py
- Default `ndirs=500` in `core.generate_kernels()` and in `trk2dictionary.run()`
- Expire the deprecated `ndirs` parameter in `amico.core.setup()`
- Expire the deprecated `filename_trk` and `gen_trk` parameters in `trk2dictionary.run()`
- Removed unused parameter `ndirs` from `trk2dictionary_c.cpp()`
- Build output goes into `build`
- Switched to proprietary license (see `LICENSE` file)
- Added clustering in trk2dictionary.run()
* geometry-based clustering using `blur_clust_thr` parameter
* anatomical information streamlines clustering based on their endpoints using `blur_clust_groupby` parameter
- Added trk2dictionary.run() parallel computation using `n_threads` parameter
- Changed internal streamlines representation using `blur_core_extent` and `blur_gauss_extent` parameters
- Added …
=> [RELEASE] v2.0.0

commit/core.pyx
When I use this modified version to fix #126, on my OSX 13.6.2 with Python 3.11.6, it seems to  and work properly.
=> [FIX] Operator is not recompiled when some parameters are changed

CHANGELOG.md, commit/core.pyx, commit/trk2dictionary/trk2dictionary.pyx, pyproject.toml
=> [RELEASE] v2.3.1

commit/core.pyx
Fix  when using `group_weights_extra`  in IC regularisation.
This pull request includes a small but important change to the `commit/core.pyx` file. The change ensures that the `weightsIC_group` variable is a copy of `dictIC_params['group_weights_extra']` instead of a reference, which helps avoid unintended side effects when modifying `weightsIC_group`.
* [`commit/core.pyx`](diffhunk://#diff-fd6ef22e60846a4eabc3965d8665f3c994eb0c693365bb7f049551bd4e9e9fc0L1000-R1000): Changed the assignment of `weightsIC_group` to use the `copy()` method to prevent unintended side effects.
=> fixed group lasso w/ extra weights

CHANGELOG.md, commit/core.pyx, pyproject.toml
Fixed problems with weighted lasso variables
=> Correction weighted lasso variables
