daducci/COMMIT

commit/operator/operator.pyxbld
commit/operator/operator_c.c
commit/trk2dictionary/trk2dictionary.cpp

Extension of the intra-cellular, extra-cellular and isotropic compartments from a maximum of 4 to a maximum of 20 compartments.

Extend the IC EC ISO compartments up to 20

---

commit/core.py

Save in the file results.pickle the x of the preconditioned problem and the x of the original problem, instead of the x used to generate the maps IC EC and ISO.
Code to load the x:
import scipy.io as sio
import pickle
file = open("results.pickle",'rb')
object_file = pickle.load(file)
x_precon = object_file[1]
x = object_file[2]

Save x preconditioned and x in results.pickle

---

commit/core.py

Solved bug #14 introduced in #13  with the reordering of the coefficients on the master.

fixed preconditioning

---

commit/trk2dictionary/trk2dictionary_c.cpp

Typo in the generation of the dictionary

small typo dictionary

---

commit/solvers.py

This PR fixes a rather big problem generated by a typo which was present in PR #36 .

fix bug in backward compatibility of group sparsity

---

commit/solvers.py

This PR solves the problem described in issue #41 .

fix assignment of group norm in the regularisation term

---

commit/solvers.py

I changed the starting point by default. From one to zero.
@barakovic, could you check if the solution is the same as the solution you obtained?

Change of default starting point. From ones to zeros.

---

commit/__init__.py
commit/core.pyx
commit/operator/operator.pyx
commit/proximals.pyx
commit/solvers.py
commit/trk2dictionary/trk2dictionary.pyx

This PR addresses COMMIT compatibility with Python 3. I tested it with both Python 2 and Python 3. @fullbat, @MarioOcampo, @barakovic can you please check as well?

Compatibility with Python 3

---

commit/__init__.py
commit/core.pyx
commit/operator/operator.pyx
commit/proximals.pyx
commit/solvers.py
commit/trk2dictionary/trk2dictionary.pyx
setup.py

Reverts daducci/COMMIT#60, because I forgot to update the internal version number

Revert "Compatibility with Python 3"

---

setup.py

I made a mistake pushing the code. Now it should be ok

Restored branch with python3 compatibility

---

commit/__init__.py
commit/core.pyx
commit/operator/operator.pyx
commit/proximals.pyx
commit/solvers.py
commit/trk2dictionary/trk2dictionary.pyx
setup.py

Revert "Revert "Compatibility with Python 3""

---

setup.py

Changed the version number to 1.2 in file setup.py to identify the version without the bug.

Updated version number to 1.2 in setup.py

---

commit/solvers.py
setup.py

Fixed EC and ISO selection in vector x to apply Omega functions

Fix EC and ISO selection for Omega functions

---

commit/proximals.pyx
commit/solvers.py
setup.py

The implementation of the projection on the L2 ball has a bug. 
To fix the bug the [Proximal Operator of the Euclidean Norm (𝐿2 Norm) ](https://math.stackexchange.com/questions/2190885/proximal-operator-of-the-euclidean-norm-l-2-norm) was implemented.

Fix proximal of L2 norm

---

CHANGELOG.md
commit/trk2dictionary/trk2dictionary.pyx
commit/trk2dictionary/trk2dictionary_c.cpp
setup.py

The length of a streamline was wrongly computed when the "blur" functionality was turned on (NB: work in progress functionality). This PR fixes that.

Fix bug in the blurring functionality (work in progress)

---

CHANGELOG.md
commit/core.pyx
commit/operator/config.py
commit/operator/operator.pyxbld
commit/trk2dictionary/trk2dictionary.pyx
setup.py

Changed the condition to create a new operator when the function `build_operator` is called.
It is required to check the functionality of the function `build_operator`  in case the parameter `build_dir` is not none.

Fix build operator

---

CHANGELOG.md
commit/trk2dictionary/trk2dictionary.pyx
setup.py

This PR implements some checks for invalid parameter values passed to the blur function. For instance, a zero radius or a negative number of samples.

Check for invalid parameter values to the blur

---

CHANGELOG.md
commit/core.pyx
commit/solvers.py
commit/trk2dictionary/trk2dictionary.pyx

Implementation of the requested change #90: the `verbose` parameters were changed to `boolean`. 
An additional change in `trk2dictionary`. 
Now it is checked that the tractogram `exists` before trying to load it, and the section `try` was removed.

Verbose bool

---

CHANGELOG.md
commit/core.pyx
commit/solvers.py

This PR updates the index of the streamlines in the groups (`structureIC`) if streamlines were not considered in the creation of the dictionary.

Mapping idxs of structureIC

---

CHANGELOG.md
commit/core.pyx
commit/info.py
commit/models.py
commit/operator/operator.pyx
commit/proximals.pyx
commit/solvers.py
commit/trk2dictionary/trk2dictionary.pyx
commit/trk2dictionary/trk2dictionary_c.cpp
setup.py

[RELEASE] v2.1.0

---

CHANGELOG.md
commit/core.pyx
commit/models.pyx
commit/operator/operator.pyx
commit/solvers.py
commit/trk2dictionary/trk2dictionary.pyx
commit/trk2dictionary/trk2dictionary_c.cpp
pyproject.toml
setup_operator.py

Updated the labels of the lesion model output masks for consistency

Updated lesion labels

---

CHANGELOG.md
commit/core.pyx
commit/models.pyx
commit/operator/operator.pyx
commit/solvers.py
commit/trk2dictionary/trk2dictionary.pyx
commit/trk2dictionary/trk2dictionary_c.cpp
pyproject.toml
setup_operator.py

- Names of the output files of the "lesion" model
- Error when calling "fit" again after "save_results"
- Minor fixes and improvements

[RELEASE] v2.4.1
